let buttonStart = document.getElementById('start'), //Начать расчет
    budgetValue = document.getElementsByClassName('budget-value')[0], //Доход
    dayBudgetValue = document.getElementsByClassName('daybudget-value')[0], //Бюджет на 1 день
    levelValue = document.getElementsByClassName('level-value')[0], //Уровень дохода
    expensesValue = document.getElementsByClassName('expenses-value')[0], //Обязательные расходы
    optionalExpensesValue = document.getElementsByClassName('optionalexpenses-value')[0], //Возможные траты
    incomeValue = document.getElementsByClassName('income-value')[0], //Дополнительный доход
    monthSavingsValue = document.getElementsByClassName('monthsavings-value')[0], //Накопления за 1 месяц
    yearSavingsValue = document.getElementsByClassName('yearsavings-value')[0], //Накопления за 1 год
    expQue1 = document.querySelectorAll('.expenses-item')[0], //Наименование 1
    expAns1 = document.querySelectorAll('.expenses-item')[1], //Цена 1
    expQue2 = document.querySelectorAll('.expenses-item')[2], //Наименование 2
    expAns2 = document.querySelectorAll('.expenses-item')[3], //Цена 2
    confirm1 = document.getElementsByTagName('button')[0], //Утвердить (Обязательные расходы)
    confirm2 = document.getElementsByTagName('button')[1], //Утвердить (необязательные расходы)
    confirm3 = document.getElementsByTagName('button')[2], //Рассчитать (Расчет дневного бюджета)
    oExp1 = document.querySelectorAll('.optionalexpenses-item')[0], // необязательные расходы 1
    oExp2 = document.querySelectorAll('.optionalexpenses-item')[1], // необязательные расходы 2
    oExp3 = document.querySelectorAll('.optionalexpenses-item')[2], // необязательные расходы 3
    posExp = document.querySelectorAll('.choose-income')[0], //Введите статьи возможного дохода
    savings = document.querySelectorAll('#savings')[0], //Есть ли накопления checkbox
    sum = document.querySelectorAll('#sum')[0],  //Сумма checlbox
    percent = document.querySelectorAll('#percent')[0], //Процент checkbox
    year = document.querySelectorAll('.year-value')[0], //Год
    month = document.querySelectorAll('.month-value')[0], //Месяц
    day = document.querySelectorAll('.day-value')[0]; //День

buttonStart.style.color = 'red';